// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQLa2w3F8kK30rhjNksbp0PF4rc4xMlNs',
    appId: '1:548567710035:web:afc2a67f5079583110c9a6',
    messagingSenderId: '548567710035',
    projectId: 'fyp-smartrecruit',
    authDomain: 'fyp-smartrecruit.firebaseapp.com',
    storageBucket: 'fyp-smartrecruit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCds4bSGRwu8d-jdeHsXxiOoMcXy9Aqqwc',
    appId: '1:548567710035:android:af64de418f5139e510c9a6',
    messagingSenderId: '548567710035',
    projectId: 'fyp-smartrecruit',
    storageBucket: 'fyp-smartrecruit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_RRIyK605_bAPDOKxRdhclQpLlcg_XA',
    appId: '1:548567710035:ios:5472e9165331772a10c9a6',
    messagingSenderId: '548567710035',
    projectId: 'fyp-smartrecruit',
    storageBucket: 'fyp-smartrecruit.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl_RRIyK605_bAPDOKxRdhclQpLlcg_XA',
    appId: '1:548567710035:ios:5472e9165331772a10c9a6',
    messagingSenderId: '548567710035',
    projectId: 'fyp-smartrecruit',
    storageBucket: 'fyp-smartrecruit.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQLa2w3F8kK30rhjNksbp0PF4rc4xMlNs',
    appId: '1:548567710035:web:e89f4289651b1de910c9a6',
    messagingSenderId: '548567710035',
    projectId: 'fyp-smartrecruit',
    authDomain: 'fyp-smartrecruit.firebaseapp.com',
    storageBucket: 'fyp-smartrecruit.firebasestorage.app',
  );
}
